# Generated by Django 6.1.1 on 2026-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('analisis', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField()),
                ('respuesta_crx', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetriaDron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria_voltaje', models.FloatField(default=14.8)),
                ('rssi_wifi', models.IntegerField(default=-65)),
                ('temperatura', models.FloatField(default=35.0)),
                ('mpu_pitch', models.FloatField(default=0.0)),
                ('mpu_roll', models.FloatField(default=0.0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
